version: "{build}"
build: off
environment:
  matrix:
    - nodejs_version: "6"
    - nodejs_version: "8"
    - nodejs_version: "9"
    - nodejs_version: "9.6"
install:
  - ps: Install-Product node $env:nodejs_version
test_script:
  - ver # prints Windows version info
  - node --version
  - npm test
